_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.8
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
            "3":
                - 2
                - 16
                - 55
            "4": 3.11.8
            "5": 0.20.1
            "8":
                - 3
            "12": 0.20.1
            "13": windows-amd64
batch:
    value: 16
epochs:
    value: 30
lr:
    value: 0.0002
seq_len:
    value: 32
